/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.myutils.logbrowser.indexer;

/**
 *
 * @author ssydoruk
 */
public enum TableType {
    UNKNOWN("UNKNOWN"),
    File("File"),
    URSRlib("URSRlib"),
    ORSTlib("ORSTlib"),
    ORSMetric("ORSMetric"),
    ORSSidUUID("ORSSidUUID"),
    ORSSidIxnID("ORSSidIxnID"),
    URSCONNIDIxnID("URSCONNIDIxnID"),
    ORSMetricExtension("ORSMetricExtension"),
    OrsLog("OrsLog"),
    OrsLink("OrsLink"),
    OrsEvent("OrsEvent"),
    OrsEsp("OrsEsp"),
    ORSUrs("ORSUrs"),
    ORSHTTP("ORSHTTP"),
    URSHTTP("URSHTTP"),
    ORSMMessage("ORSMMessage"),
    MsgTServer("MsgTServer"),
    MsgOCServer("MsgOCServer"),
    MsgURServer("MsgURServer"),
    MsgORServer("MsgORServer"),
    MsgStatServer("MsgStatServer"),
    URSSTAT("URSSTAT"),
    TLib("TLib"),
    StSAction("StSAction"),
    StSTEvent("StSTEvent"),
    StSRequestHistory("StSRequestHistory"),
    Handler("Handler"),
    CIFaceRequest("CIFaceRequest"),
    ISCC("ISCC"),
    SIP("SIP"),
    ConnID("ConnID"),
    IxnDB("IxnDB"),
    URSTlib("URSTlib"),
    URSStrategy("URSStrategy"),
    URSCONNIDSID("URSCONNIDSID"),
    URSRI("URSRI"),
    Trigger("Trigger"),
    JSon("JSon"),
    CampaignGroup("CampaignGroup"),
    OCSAssignment("OCSAssignment"),
    OCSRecCreate("OCSRecCreate"),
    OCSTLib("OCSTLib"),
    OCSIxn("OCSIxn"),
    OCSClient("OCSClient"),
    OCSHTTP("OCSHTTP"),
    OCSDBActivity("OCSDBActivity"),
    OCSCG("OCSCG"),
    OCSPASessionInfo("OCSPASessionInfo"),
    OCSPAAgentInfo("OCSPAAgentInfo"),
    OCSPAEventInfo("OCSPAEventInfo"),
    OCSStatEvent("OCSStatEvent"),
    OCSSCXMLTreatment("OCSSCXMLTreatment"),
    OCSSCXMLScript("OCSSCXMLScript"),
    Ixn("Ixn"),
    MsgIxnServer("MsgIxnServer"),
    StStatus("StStatus"),
    OCSTreatment("OCSTreatment"),
    ConfigUpdate("ConfigUpdate"),
    TLibProxied("Proxied"),
    URSStrategyInit("URSStrategyInit"),
    SIPMS("SIPMediaServer"),
    WSTlib("WSTlib"),
    StCapacity("StCapacity"),
    SIPEP("SIPEP"),
    VOIPEP("VOIPEP"),
    URSWaiting("URSWaiting"),
    IxnSS("IxnSS"),
    URSVQ("URSVirtualQueue"),
    URSTargetSet("URSTargetSet"),
    ORSSidSid("ORSSidSid"),
    WSStat("WSStat"),
    WSConf("WSConf"),
    WSEServ("WSEServ"),
    MsgRM("MsgRM"),
    MsgMCP("MsgMCP"),
    MsgSCServer("MsgSCServer"),
    MsgWWECloud("MsgWWECloud"),
    SCSSelfStatus("SCSSelfStatus"),
    SCSAppStatus("SCSAppStatus"),
    OCSIcon("OCSIcon"),
    MsgWWE("MsgWWE"),
    WWETable("WWETable"),
    WWEException("WWEException"),
    MsgDBServer("MsgDBServer"),
    MsgGMS("MsgGMS"),
    GMSPOST("GMSPOST"),
    GMSORSMessage("GMSORSMessage"),
    URSAgentGroupTable("URSAgentGroupTable"),
    OCSPredInfo("OCSPredInfo"),
    ObjectDBID("ObjectDBID"),
    MsgLCAServer("MsgLCAServer"),
    LCAAppStatus("LCAAppStatus"),
    LCAClient("LCAClient"),
    ORSCallID("ORSCallID"),
    CSUpdate("CSClientRequest1"),
    MsgConfServer("MsgConfServer"),
    CSClientConf("CSClientConf"),
    CSClientConnect("CSClientConnect"),
    ORSAlarm("ORSAlarm"),
    GMSStart("GMSStart"),
    ORSSessionStart("ORSSessionStart"),
    SIP1536Other("SIP1536Other"),
    WWECloud("wwecloudTEvents"),
    SIP1536Trunk("SIP1536Trunk"),
    SIP1536ReqResp("SIP1536ReqResp"),
    TLIBTimerRedirect("TimerRedirect"),
    CSClientRequest("CSClientRequest"),
    WWECloudAuth("WWEAuth"),
    WWECloudException("WWECloudEx"),
    WWECloudLog("WWELog"),
    ApacheWeb("ApacheWeb"),
    WWEMessage("WWEMessage"),
    WWEBayeuxMessage("WWEBayeuxMessage"),
    WWEUCSMessage("WWEUCSMessage"),
    VXMLIntStepsTable("vxmlIntSteps"),
    WWEIxnMessage("WWEIxnMessage"),
    WWEUCSConfigMessage("WWEUCSConfig"),
    WWEStatServerMessage("WWEStatServer"),
    SCSClientLogMessage("SCSClientLog"),
    GMSStatServerMessage("GMSSS"),
    GMSWebClientMessage("GMSWebClient"),
    IxnGMS("IxnGMS"),
    SCSAlarm("SCSAlarm"),
    IxnNonIxn("IxnNonIxn"),
    HTTP_TO_URS("httpTOurs");

    private final String name;

    private TableType(String s) {
        name = s;
    }

    public boolean equalsName(String otherName) {
        return (otherName == null) ? false : name.equals(otherName);
    }

    @Override
    public String toString() {
        return this.name.toLowerCase();
    }

}
