/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.myutils.logbrowser.inquirer.gui;

import com.myutils.logbrowser.indexer.FileInfoType;
import com.myutils.logbrowser.inquirer.IQueryResults;
import com.myutils.logbrowser.inquirer.NameID;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemListener;
import java.sql.SQLException;
import java.util.ArrayList;

/**
 * @author ssydoruk
 */
public class JPAppSelect extends javax.swing.JPanel {

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<String> jcbApps;

    public JPAppSelect(FileInfoType fileInfoType) throws Exception {
        this();
    }

    /**
     * Creates new form JPAppSelect
     */
    public JPAppSelect() {
        initComponents();

    }

    public void addActionListener(ActionListener l) {
        jcbApps.addActionListener(l);
    }

    public void loadApps() throws SQLException {

        loadApps(null);
//        jcbApps.setSelectedIndex(0);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jcbApps = new javax.swing.JComboBox<>();

        jLabel1.setText("Application");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcbApps, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(jcbApps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void addItemListener(ItemListener aListener) {
        jcbApps.addItemListener(aListener);
    }

    public void actionPerformed(ActionEvent e) {
        jcbApps.actionPerformed(e);
    }
    // End of variables declaration//GEN-END:variables

    public int getAppID() {
        return ((NameID) jcbApps.getSelectedItem()).getId();
    }

    public void loadApps(FileInfoType fileInfoType) throws SQLException {
        ArrayList<NameID> refNameIDs = IQueryResults.getAllApps(this, fileInfoType);
        DefaultComboBoxModel defaultComboBoxModel = new DefaultComboBoxModel(refNameIDs.toArray(new NameID[refNameIDs.size()]));
        jcbApps.setModel(defaultComboBoxModel);
        if (refNameIDs.size() > 0) {
            defaultComboBoxModel.setSelectedItem(refNameIDs.get(0));
        }
//        jcbApps.setSelectedIndex(0);

    }
}
