/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.myutils.logbrowser.inquirer.gui;

import com.myutils.logbrowser.inquirer.inquirer;
import java.text.NumberFormat;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.NumberFormatter;

/**
 *
 * @author ssydoruk
 */
public class JPSecSelect extends javax.swing.JPanel {

    /**
     * Creates new form JPSecSelect
     */
    public JPSecSelect() {
        initComponents();
        initFormats(1, 1);

//    NumberFormat a = NumberFormat.getNumberInstance();
//    NumberFormatter b = new NumberFormatter(a);
//    DefaultFormatterFactory c = new DefaultFormatterFactory(b);
//    jFormattedTextField1.setFormatterFactory(c);
    }

    private void initFormats(int min, int def) {
        NumberFormat format = NumberFormat.getInstance();
        NumberFormatter formatter = new NumberFormatter(format);
        formatter.setValueClass(Integer.class);
        formatter.setMinimum(min);
        formatter.setMaximum(Integer.MAX_VALUE);
        formatter.setAllowsInvalid(false);
        jtfSeconds.setFormatterFactory(new DefaultFormatterFactory(formatter));
        jtfSeconds.setValue(def);
        jtfSeconds.setColumns(6);
    }

    public JPSecSelect(int min, int def) {
        initComponents();
        initFormats(min, def);
    }

    public void setTextStart(String text) {
        lbStart.setText(text);
    }

    public void setTextEnd(String text) {
        lbEnd.setText(text);
    }

    public int getSeconds() {
        try {
            Object value = jtfSeconds.getValue();
            return (int) jtfSeconds.getValue();
        } catch (Exception e) {
            inquirer.ExceptionHandler.handleException(this.getClass().toString(), e);

            return 1;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbStart = new javax.swing.JLabel();
        jtfSeconds = new javax.swing.JFormattedTextField();
        lbEnd = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.X_AXIS));

        lbStart.setText("Sample each");
        add(lbStart);

        jtfSeconds.setText("1");
        add(jtfSeconds);

        lbEnd.setText("second(s)");
        add(lbEnd);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField jtfSeconds;
    private javax.swing.JLabel lbEnd;
    private javax.swing.JLabel lbStart;
    // End of variables declaration//GEN-END:variables

}
