/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.myutils.logbrowser.inquirer.gui;

import Utils.ScreenInfo;
import com.myutils.logbrowser.common.JSRunner;
import com.myutils.logbrowser.common.RecordPrintout;
import com.myutils.logbrowser.inquirer.ILogRecord;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.ScrollPaneConstants;
import org.apache.commons.lang3.StringUtils;
import org.fife.ui.rsyntaxtextarea.RSyntaxTextArea;
import org.fife.ui.rsyntaxtextarea.SyntaxConstants;
import org.fife.ui.rtextarea.RTextScrollPane;

/**
 *
 * @author ssydoruk
 */
public class ShowFullMessage extends javax.swing.JFrame {

    private ReportFrameQuery parentForm;
    RSyntaxTextArea detailedMessage;

    /**
     * Creates new form ShowFullMessage
     */
    public ShowFullMessage() {
        initComponents();
        detailedMessage = new RSyntaxTextArea();
        detailedMessage.setCodeFoldingEnabled(true);

        RTextScrollPane sp = new RTextScrollPane(detailedMessage);
        detailedMessage.setWrapStyleWord(true);
        detailedMessage.setLineWrap(true);
        pDetailedMessage.add(sp);
    }

    ShowFullMessage(ReportFrameQuery aThis) {
        this();
        parentForm = aThis;
        ScreenInfo.CenterWindowTopMaxWidth(this);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
//                if (fullMsg != null) {
//                    fullMsg.dispose();
//                    fullMsg = null;
//                }
                parentForm.fullMsgClosed();
                super.windowClosing(e); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void windowGainedFocus(WindowEvent e) {
//                if (fullMsg != null) {
//                    fullMsg.setVisible(true);
//                }
                super.windowGainedFocus(e); //To change body of generated methods, choose Tools | Templates.
            }

        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        spFullMessage = new javax.swing.JScrollPane();
        jtaMessageText = new javax.swing.JTextArea();
        pDetailedMessage = new javax.swing.JPanel();

        setAutoRequestFocus(false);
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowDeactivated(java.awt.event.WindowEvent evt) {
                formWindowDeactivated(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jtaMessageText.setEditable(false);
        jtaMessageText.setColumns(20);
        jtaMessageText.setLineWrap(true);
        jtaMessageText.setRows(5);
        jtaMessageText.setWrapStyleWord(true);
        spFullMessage.setViewportView(jtaMessageText);

        jSplitPane1.setLeftComponent(spFullMessage);

        pDetailedMessage.setLayout(new java.awt.BorderLayout());
        jSplitPane1.setRightComponent(pDetailedMessage);

        getContentPane().add(jSplitPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        parentForm.fullMsgClosed();
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void formWindowDeactivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowDeactivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowDeactivated

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextArea jtaMessageText;
    private javax.swing.JPanel pDetailedMessage;
    private javax.swing.JScrollPane spFullMessage;
    // End of variables declaration//GEN-END:variables

    void showMessage(String GetFileBytes) {
//        System.out.println("before " + jtaMessageText.getText());
//        jtaMessageText.setText("g");
//        setFocusableWindowState(false);
        jtaMessageText.setText(GetFileBytes);
        jtaMessageText.setCaretPosition(0);
//        toFront();
//        parentForm.toFront();
//        System.out.println("after " + jtaMessageText.getText());
//        Document document = jtaMessageText.getDocument();
//        System.out.println("aafter " + document.toString());
//        jtaMessageText.revalidate();
//        jtaMessageText.repaint();
//        setVisible(false);
//        setVisible(true);
//        validate();
    }

    void showMessage(String recordDisplayScript, ILogRecord record) {
        detailedMessage.setText("");
        if (StringUtils.isEmpty(recordDisplayScript)) {
            showMessage(record.getBytes());
        } else {
            RecordPrintout recPrintout = JSRunner.evalFullRecordPrintout(recordDisplayScript, record);
            showMessage(recPrintout.fullMessage);
            if(StringUtils.isNotEmpty(recPrintout.detailsMessage)){
                detailedMessage.setText(recPrintout.detailsMessage);
                detailedMessage.setSyntaxEditingStyle(SyntaxConstants.SYNTAX_STYLE_JSON);

            }
        }
    }
}
