/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.myutils.logbrowser.inquirer;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;

/**
 * @author ssydoruk
 */
public class AggregatesPanel extends javax.swing.JPanel {

    ButtonGroup group = new ButtonGroup();
    JPanel radioPanel;
    JScrollPane jScrollPane1;
    private IAggregateQuery AggregateQuerySelected = null;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jpAggregateParams;
    private javax.swing.JPanel jpAggregates;
    private javax.swing.JPanel jpReportSelection;
    private javax.swing.JRadioButton jrbPrintToFile;
    private javax.swing.JRadioButton jrbPrintToScreen;
    /**
     * Creates new form AggregateParams
     */
    public AggregatesPanel() {
        initComponents();
    }
    AggregatesPanel(ArrayList<IAggregateQuery> queries) {
        this();
        //    jpAggregateParams.setLayout(new FlowLayout());
        radioPanel = new JPanel();
        radioPanel.setLayout(new BoxLayout(radioPanel, BoxLayout.Y_AXIS));
        for (IQueryResults query : queries) {
            JReferencingButton btn = new JReferencingButton<>(query.getName(), (IAggregateQuery) query);
            btn.addActionListener(new ActionListener() {

                @Override
                public void actionPerformed(ActionEvent e) {
                    btnAction(e);
                }

            });
            group.add(btn);
            radioPanel.add(btn);
        }
        jpAggregates.setLayout(new FlowLayout(HEIGHT));
//        paramPanel.add(radioPanel);
        jScrollPane1 = new JScrollPane(radioPanel);
        jScrollPane1.setLayout(new ScrollPaneLayout());
        jpAggregates.add(jScrollPane1);
//        group.clearSelection();
//        group.setSelected(group.getElements().nextElement().getModel(), true);
        group.getElements().nextElement().doClick();
        jpReportSelection.setMaximumSize(jpReportSelection.getPreferredSize());
        jpReportSelection.setMinimumSize(jpReportSelection.getPreferredSize());
//        radioPanel.setSize(100, 200);
//        jScrollPane1.add(radioPanel,CENTER_ALIGNMENT);
    }

    public IAggregateQuery getSelected() {
        return AggregateQuerySelected;
    }

    public boolean isPrintToScreen() {
        return jrbPrintToScreen.isSelected();
    }

    private void btnAction(ActionEvent e) {
        JReferencingButton<IAggregateQuery> qr = (JReferencingButton<IAggregateQuery>) e.getSource();
        AggregateQuerySelected = qr.getValue();
        JPanel cfgPane = qr.getValue().getJpConfig();
        jpAggregateParams.removeAll();
        if (cfgPane != null) {
            jpAggregateParams.add(cfgPane);
        }
        jpAggregateParams.setVisible(cfgPane != null);
        jpAggregateParams.invalidate();
        Window f2 = SwingUtilities.getWindowAncestor(this);
        if (f2 != null) {
            f2.pack();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jpReportSelection = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jpAggregates = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jrbPrintToScreen = new javax.swing.JRadioButton();
        jrbPrintToFile = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jpAggregateParams = new javax.swing.JPanel();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jpReportSelection.setLayout(new javax.swing.BoxLayout(jpReportSelection, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.PAGE_AXIS));

        jpAggregates.setBorder(javax.swing.BorderFactory.createTitledBorder("Report available"));
        jpAggregates.setLayout(new java.awt.BorderLayout());
        jPanel2.add(jpAggregates);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.PAGE_AXIS));

        buttonGroup1.add(jrbPrintToScreen);
        jrbPrintToScreen.setSelected(true);
        jrbPrintToScreen.setText("Print to screen");
        jPanel1.add(jrbPrintToScreen);

        buttonGroup1.add(jrbPrintToFile);
        jrbPrintToFile.setText("Print to file");
        jPanel1.add(jrbPrintToFile);

        jPanel2.add(jPanel1);

        jpReportSelection.add(jPanel2);
        jpReportSelection.add(jPanel3);

        add(jpReportSelection);

        jpAggregateParams.setBorder(javax.swing.BorderFactory.createTitledBorder("Report settings"));
        jpAggregateParams.setLayout(new java.awt.BorderLayout());
        add(jpAggregateParams);
    }// </editor-fold>//GEN-END:initComponents

    public class JReferencingButton<T> extends JRadioButton {

        private T value;

        private JReferencingButton(String name, T qr) {
            super(name);
            setValue(qr);
        }

        public T getValue() {
            return this.value;
        }

        public void setValue(T value) {
            this.value = value;
        }
    }
    // End of variables declaration//GEN-END:variables
}
