/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.myutils.logbrowser.inquirer;

import Utils.Pair;
import javax.swing.ComboBoxModel;

/**
 *
 * @author ssydo
 */
public class AllSelection extends javax.swing.JPanel {

    /**
     * Creates new form AllSelection
     */
    public AllSelection(ComboBoxModel sortFieldsModel) {
        initComponents();
        cbField.setModel(sortFieldsModel);
        spRecords.setValue(10);
        makeEditableMax();
    }

    public boolean isAscendingSorting() {
        return rbAscending.isSelected();
    }

    public Integer getMaxRecords() {
        return (rbMaxRecords.isSelected()) ? (Integer) spRecords.getValue() : -1;
    }

    public String getSortField() {
        Pair<String, String> selectedItem = (Pair< String, String>) cbField.getSelectedItem();

        return (selectedItem == null) ? null : selectedItem.getValue();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgSortOrder = new javax.swing.ButtonGroup();
        bgMessagesNumber = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        cbField = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        rbAscending = new javax.swing.JRadioButton();
        rbDescending = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        rbAllRecords = new javax.swing.JRadioButton();
        jPanel8 = new javax.swing.JPanel();
        rbMaxRecords = new javax.swing.JRadioButton();
        spRecords = new javax.swing.JSpinner();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Sorting"));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Field"));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        cbField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel6.add(cbField);

        jPanel4.add(jPanel6);

        jPanel2.add(jPanel4);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Order"));

        bgSortOrder.add(rbAscending);
        rbAscending.setText("Ascending");

        bgSortOrder.add(rbDescending);
        rbDescending.setSelected(true);
        rbDescending.setText("Descending");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbDescending)
                    .addComponent(rbAscending))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbAscending)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbDescending)
                .addContainerGap())
        );

        jPanel2.add(jPanel3);

        add(jPanel2);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Retrieve messages"));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.PAGE_AXIS));

        bgMessagesNumber.add(rbAllRecords);
        rbAllRecords.setText("All");
        rbAllRecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAllRecordsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(rbAllRecords)
                .addGap(0, 170, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(rbAllRecords)
                .addContainerGap())
        );

        jPanel1.add(jPanel7);

        bgMessagesNumber.add(rbMaxRecords);
        rbMaxRecords.setSelected(true);
        rbMaxRecords.setText("Not more than");
        rbMaxRecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMaxRecordsActionPerformed(evt);
            }
        });

        spRecords.setModel(new javax.swing.SpinnerNumberModel());

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(rbMaxRecords)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spRecords, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 19, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbMaxRecords)
                    .addComponent(spRecords, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel8);

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents

    private void rbAllRecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAllRecordsActionPerformed
        // TODO add your handling code here:
        makeEditableMax();
    }//GEN-LAST:event_rbAllRecordsActionPerformed

    private void rbMaxRecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMaxRecordsActionPerformed
        // TODO add your handling code here:
        makeEditableMax();
    }//GEN-LAST:event_rbMaxRecordsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgMessagesNumber;
    private javax.swing.ButtonGroup bgSortOrder;
    private javax.swing.JComboBox<String> cbField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JRadioButton rbAllRecords;
    private javax.swing.JRadioButton rbAscending;
    private javax.swing.JRadioButton rbDescending;
    private javax.swing.JRadioButton rbMaxRecords;
    private javax.swing.JSpinner spRecords;
    // End of variables declaration//GEN-END:variables

    private void makeEditableMax() {
        spRecords.setEnabled(rbMaxRecords.isSelected());
    }
}
