package com.myutils.logbrowser.inquirer;

public enum DialogItem {

    APP_LOG_MESSAGES("Log messages"),
    APP_LOG_MESSAGES_TYPE("Type"),
    APP_LOG_MESSAGES_TYPE_LEVEL("Level"),
    APP_LOG_MESSAGES_TYPE_MESSAGE_ID("Message ID"),
    CONFIGUPDATES("Config updates"),
    CONFIG_UPDATES_TYPE("Type"),
    IXN("Interactions"),
    TLIB_CALLS("Calls"),
    TLIB_CALLS_TEVENT("TEvents"),
    TLIB_CALLS_SIP("SIP"),
    TLIB_CALLS_TEVENT_NAME("Name"),
    TLIB_CALLS_SIP_NAME("SIP method"),
    TLIB_CALLS_SIP_ENDPOINT("Endpoint"),
    TLIB_CALLS_SIP_CALL_ID("Call-ID"),
    OCSCG("Campaign Group"),
    OCSCG_PASESSIONINFO("PA Session Info"),
    OCS_CG_PA_AGENT_INFO("PA agent Info"),
    OCSCG_PAEVENTINFO("PA event Info"),
    OCSCG_CAMPAIGNGROUP("Campaign group"),
    OCSCG_AGENT_ASSIGNMENT("Agent Assignment"),
    OCSCG_CLIENT("Client requests"),
    OCS("Outbound call"),
    OCSCALL_TEVENT("TEvents"),
    OCS_CALL_TEVENT_NAME("Name"),
    OCSCALL_SCXML("OCS SCXML"),
    OCSCALL_DATABASE("Database"),
    OCSCALL_IXNSERVER("Interaction Server"),
    OCSAGENT("Campaign Agent"),
    TLIB_CALLS_SIP_PEERIP("Peer IP"),
    TLIB_CALLS_TSCP("TServer common library"),
    TLIB_CALLS_ISCC("ISCC messages"),
    TLIB_CALLS_JSON("Feature Server JSON messages"),
    IXN_EVENT("Interaction"),
    IXN_NONEVENT("TLib events"),
    IXN_IXN_EVENT_NAME("Name"),
    TLIB_CALLS_TEVENT_DN("DN/workflow object"),
    IXN_IXN_EVENT_DN("workflow object"),
    ORS_TEVENTS("Events"),
    ORS_STRATEGY("Strategy"),
    ORS_STRATEGY_METRIC("Metric"),
    ORS_ORSURS("ORS to URS communications"),
    URS("URS strategy"),
    ORS("ORS SCXML strategy"),
    URS_EVENTS("Events"),
    URS_STRATEGY("Strategy"),
    URS_RLIB("RLIB"),
    ORS_TEVENTS_NAME("Name"),
    ORS_TEVENTS_DN("DN"),
    ORS_ORSURS_METHOD("ORS Method"),
    URS_EVENTS_NAME("Name"),
    URS_EVENTS_DN("Routing objects"),
    OCS_CALL_TEVENT_DN("DN"),
    OCSCG_CAMPAIGNGROUP_CGNAME("Campaign Group name"),
    OCSCG_CAMPAIGNGROUP_CAMPAIGN("Campaign name"),
    OCS_DATABASE_REQUESTTYPE("DB Server request/response"),
    OCS_DATABASE_DBSERVER("DBServer app"),
    OCS_CG_REQUEST("Request type"),
    URS_EVENTS_SERVER("Server"),
    OCS_CALL_TEVENT_SERVER("Server"),
    TLIB_CALLS_ISCC_NAME("name"),
    OCSCG_CLIENT_REQUEST("OCS request"),
    OCSCG_PAEVENTINFO_STATTYPE("Stattype"),
    URS_STRATEGY_MESSAGE("Strategy message"),
    OCSCALL_PAAI("PA Agent info"),
    OCSCALL_PAEVI("PA Event info"),
    OCSCALL_RECCR("Create record"),
    OCSCALL_HTTP("HTTP"),
    STAT_CALLS("Calls"),
    STATCALLS_TEVENT("TEvents"),
    STATCALLS_TEVENT_NAME("Name"),
    STATCALLS_TEVENT_DN("DN"),
    ORS_SESSION("ORS session creation"),
    ORS_HTTP("ORS HTTP requests"),
    OCSAGENT_PAAI("PA Agent info"),
    OCSAGENT_STAT("Statistic"),
    OCSAGENT_TEVENTS("TLibrary events"),
    STATAGENTPLACE("Agent/Place"),
    STATCLIENT("Client"),
    STATAGENTPLACE_AGENT("Agent"),
    STATCLIENT_NAME("Name"),
    STATAGENTPLACE_AGENT_NAME("Name"),
    STATCLIENT_NAME_NAME("Name"),
    OCSCALL_TREATMENT("Outbound treatment"),
    TLIB_CALLS_SIP_DIRECTION("direction"),
    TLIB_CALLS_TEVENT_DIRECTION("direction"),
    URS_RI("URS Web interface"),
    STATAGENTPLACE_STATUS("StatStatus"),
    STATAGENTPLACE_STATUS_NAME("Name"),
    URS_AGENTDN("Agent/DN/Place"),
    ORS_STRATEGY_METRICEXT("Extension"),
    CONFIGUPDATES_CONFIGUPDATES("Config updates"),
    CONFIGUPDATES_CONFIGUPDATES_OBJECTTYPE("Object type"),
    TLIB_SOURCE("Source application"),
    TLIB_CALLS_SOURCE("Source application"),
    URS_AGENTDN_NEWSTAT("New StatType"),
    URS_AGENTDN_STATSWITCH("Voice DN switch"),
    URS_AGENTDN_AGENT("Agent name"),
    OCSCALL_DESKTOP("Desktop protocol"),
    TLIB_CALLS_TEVENT_AGENT("Agent ID"),
    OCSAGENT_PAAI_AGENT("Agent"),
    OCSAGENT_PAAI_STATTYPE("Stat type"),
    OCSAGENT_PAAI_CALLTYPE("Call type"),
    OCSAGENT_STAT_STAT("Stat name"),
    OCSAGENT_STAT_AGENT("Agent name"),
    OCSAGENT_STAT_PLACE("Place"),
    OCSAGENT_STAT_DN("DN"),
    OCSAGENT_STAT_STATTYPE("StatType"),
    URS_STRATEGY_SCRIPT("Script"),
    OCSCALL_PAEVI_CALLRESULT("Call result"),
    STATAGENTPLACE_PLACE("Place"),
    STATAGENTPLACE_PLACE_NAME("Name"),
    URS_VQ("Virtual Queue"),
    URS_RLIB_METHOD("ORS Method"),
    SCS("Application status"),
    SCSSCS("SCS application"), SCS_Application("Application"), SCS_Application_NAME("name"),
    IXN_IXN_EVENT_ATTR1("Attribute 1"),
    IXN_IXN_EVENT_ATTR2("Attribute 2"),
    URS_EVENTS_ATTR1("Attribute 1"),
    TLIB_CALLS_TEVENT_ATTR1("Attribute 1"),
    TLIB_CALLS_TEVENT_ATTR2("Attribute 2"),
    OCSCALL_HTTP_REQUEST("HTTP request"),
    CUSTOM("Custom"),
    CUSTOM_COMP("Key"),
    OCSCALL_OCSICON("OCS Icon messages"),
    OCSCALL_OCSICON_EVENT("Event"), OCSCALL_OCSICON_CAUSE("Cause"),
    WWEEXCEPTIONS("Java exceptions"), GMStoURS("GMS to URS"), GMStoURS_PARAMS_NAME("Request"), GMStoURS_PARAMS("Request"),
    GMSPOST("HTTP POST"), GMSPOST_PARAMS("POST parameters"), GMSPOST_PARAMS_EVENT("Event"), GMSPOST_PARAMS_URIID("URIID"),
    ORS_IXN("Interactions"), ORS_IXN_NAME("Event name"), LCAClient("Clients"),
    ORS_TEVENTS_SOURCE("Source"),
    CONFSERV_REQUESTS("Modification requests"),
    CONFSERV_REQUESTS_OBJTYPE("Object type"),
    CONFSERV_REQUESTS_APP("Modifier app"),
    CONFSERV_REQUESTS_USER("Modified by"),
    CONFSERV_REQUESTS_CLIENTTYPE("Client type"),
    CONFSERV_REQUESTS_OPERATION("Operation"), CONFSERV_CONFIGNOTIF("Config notifications"),
    CONFSERV_CLIENTCONN("Client connects"), CONFSERV_REQUESTS_HOSTPORT("host:port"), CONFSERV_CLIENTCONN_ISCONNECT("is connected"),
    CONFSERV_CONFIGNOTIF_APP("Application"),
    CONFSERV_CONFIGNOTIF_CLIENTTYPE("App type"), CONFSERV_CONFIGNOTIF_OBJTYPE("Object type"),
    CONFSERV_CLIENTCONN_USER("User"),
    CONFSERV_CLIENTCONN_HOSTPORT("Host:port"),
    IXN_IXN_EVENT_APP("Application"), IXN_IXN_EVENT_MEDIA("Media"), ORSALARM("ORS Alarm"),
    SIP1536("SIP diagnostics"), SIP1536_MISC("Miscelaneous"),
    SIP1536_TRUNK("Trunk statistics"),
    SIP1536_SIP("SIP Messages"),
    SIP1536_TRUNK_NAME("Name"),
    SIP1536_SIP_MESSAGE("SIP Message name"), SIP1536_MISC_KEY("key"),
    STATCALLS_IXNEVENTS("Interactions"),
    STATCALLS_IXNEVENTS_QUEUE("Queue"),
    STATCALLS_IXNEVENTS_NAME("name"),
    STATCALLS_IXNEVENTS_place("Place"),
    STATCALLS_IXNEVENTS_AGENT("Agent"),
    TLIB_CALLS_TIMER("Timer events"),
    TLIB_CALLS_TIMER_NAME("Event name"),
    TLIB_CALLS_TIMER_CAUSE("Cause"),
    WWECLOUDAUTH("Agents authentication"),
    WWECLOUDAUTH_RESPONSE("Auth result"),
    WWECLOUDAUTH_RESPONSE_RESULT("Result"),
    WWECLOUDAUTH_RESPONSE_AGENT("Agent"),
    WWEEXCEPTIONS_EX("Exception attributes"),
    WWEEXCEPTIONS_EX_NAME("Exception name"),
    WWEEXCEPTIONS_EX_MSG("Exception message"),
    WWELOGMESSAGE("WWE log messages"),
    WWELOGMESSAGE_MSG("Log message"),
    WWELOGMESSAGE_MSG_LEVEL("Log level"),
    WWELOGMESSAGE_MSG_TEXT("Message text"),
    MCP_STRATEGY("MCP strategy"),
    MCP_STRATEGY_STEPS("Strategy steps"),
    CONFSERV_CONFIGNOTIF_OBJNAME("Modified object name"),
    APACHEMSG("Apache log messages"),
    APACHEMSG_PARAMS("Message params"),
    APACHEMSG_PARAMS_IP("IP Address of the client"),
    APACHEMSG_PARAMS_HTTPCODE("HTTP response code"),
    APACHEMSG_PARAMS_HTTPMETHOD("HTTP method"),
    APACHEMSG_PARAMS_HTTPURL("HTTP URL"),
    WWEDEBUGMESSAGE("WWE cloud log messages"),
    WWEDEBUGMESSAGE_PARAMS("Message params"),
    WWEDEBUGMESSAGE_PARAMS_IP("Party IP"),
    WWEDEBUGMESSAGE_PARAMS_HTTPURL("URL"),
    WWEDEBUGMESSAGE_PARAMS_JAVACLASS("JAVA class"),
    WWEDEBUGMESSAGE_PARAMS_LEVEL("Message level"),
    ORS_STRATEGY_METRICPARAM1("Metric param1"),
    WWEUCSMESSAGE("UCS messages"),
    WWEUCSMESSAGE_PARAMS("UCS message specific"),
    WWEUCSMESSAGE_PARAMS_NAME("Message name"),
    WWEBAYEUXMESSAGE("Bayeux messages"),
    WWEBAYEUXMESSAGE_PARAMS("Bayeux specific"),
    WWEBAYEUXMESSAGE_PARAM1_NAME("Param1"),
    WWEBAYEUXMESSAGE_PARAM2_NAME("Param2"),
    WWECONFIGMESSAGE("Config related messages"),
    WWECONFIGMESSAGE_PARAMS("Config specific"),
    WWECONFIGMESSAGE_PARAMS_NAME("Message name"),
    WWEDEBUGMESSAGE_PARAMS_MESSAGE("Message text"),
    WWEDEBUGMESSAGE_PARAMS_USER("User name"),
    IXN_IXN_EVENT_AGENT("Agent name"),
    IXN_IXN_EVENT_PLACE("Place name"),
    TLIB_CALLS_TEVENT_DNIS("DNIS"),
    TLIB_CALLS_TEVENT_ANI("ANI"),
    SCSClientLog("Client log messages"),
    SCSClientLog_params("message params"),
    SCSALARMS("Alarms"),
    SCSALARMS_params("Alarm parameters"),
    SCSALARMS_params_ALARMNAME("Alarm name"),
    SCSALARMS_params_APPNAME("Application name"),
    SCSALARMS_params_CATEGORY("Category"), SCSALARMS_params_ALARMSTATE("Alarm state"), TLIB_CALLS_TEVENT_Place("Place"),
    GMSWEBREQUESTS("GMS web requests"), GMSWEBREQUESTS_PARAMS("Parameters"), GMSWEBREQUESTS_PARAMS_URL("URL"),
    IXN_NONIXN_EVENT_NAME("Event"), IXN_NONIXN_EVENT_ATTR1("Attribute 1"), IXN_NONIXN_EVENT_ATTR2("Attribute 2"),
    IXN_NONIXN_EVENT_DN("DN"), IXN_NONIXN_EVENT_EVENT("Distributed event"), URS_RI_FUNCTION("Method"), URS_RI_SUBFUNCTION("Submethod"),
    URS_RI_PARAM1("Function param 1"),
    URS_RI_PARAM2("Function param 2"),
    URS_RI_PARAM3("Function param 3"),
    URS_RI_PARAM4("Function param 4"),
    URS_RI_PARAM5("Function param 5"),
    MCP_STRATEGY_STEPSPARAMS1("Strategy parameters 1"),
    MCP_STRATEGY_STEPSPARAMS2("Strategy parameters 2"),
    URS_HTTP("HTTP requests to URS"),
    URS_HTTP_METHOD("HTTP method"),
    URS_HTTP_URI("HTTP URI"),;

    private final String name;

    DialogItem(String s) {
        name = s;
    }

//    public boolean equals(DialogItem item) {
//        
//    }
    public boolean equalsName(String otherName) {
        return otherName != null && name.equalsIgnoreCase(otherName);
    }

    @Override
    public String toString() {
        return this.name;
    }

}
