/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.myutils.logbrowser.inquirer;

import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.io.File;

/**
 * @author ssydoruk
 */
public class FileOutSettings extends javax.swing.JPanel {

    static JFileChooser chooser = null;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgAllFields;
    private javax.swing.ButtonGroup btgFieldDelimiter;
    private javax.swing.ButtonGroup btgHeaders;
    private javax.swing.ButtonGroup btgOutputFormat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JButton jbChooseFile;
    private javax.swing.JCheckBox jcbAccessFiles;
    private javax.swing.JCheckBox jcbLimitQueryResults;
    private javax.swing.JCheckBox jcbPrintFileLine;
    private javax.swing.JCheckBox jcbPrintRecordType;
    private javax.swing.JCheckBox jcbSort;
    private javax.swing.JPanel jpDelimiter;
    private javax.swing.JPanel jpOutputFormat;
    private javax.swing.JPanel jpQuerySettings;
    private javax.swing.JPanel jpReportContent;
    private javax.swing.JRadioButton jrbAllFields;
    private javax.swing.JRadioButton jrbComma;
    private javax.swing.JRadioButton jrbExcel;
    private javax.swing.JRadioButton jrbFieldsFormatted;
    private javax.swing.JRadioButton jrbFull;
    private javax.swing.JRadioButton jrbHeaderOnTop;
    private javax.swing.JRadioButton jrbOther;
    private javax.swing.JRadioButton jrbPrependHeader;
    private javax.swing.JRadioButton jrbSimple;
    private javax.swing.JRadioButton jrbTab;
    private javax.swing.JRadioButton jrbTube;
    private javax.swing.JSpinner jsMaxQueryLines;
    private javax.swing.JTextField jtfOther;
    private javax.swing.JTextField jtfOutFile;
    /**
     * Creates new form FileOutSettings
     */
    public FileOutSettings() {
        initComponents();
        setHeadersEnable();
        setSeparatorEnabled();
        jsMaxQueryLines.setValue(inquirer.getCr().getMaxQueryLines());
        enableJtfOther();
    }

    public boolean isSort() {
        return jcbSort.isSelected();
    }

    public boolean isFull() {
        return jrbFull.isSelected();
    }

    public boolean isExcel() {
        return jrbExcel.isSelected();
    }

    public String getOutFile() {
        return jtfOutFile.getText();
    }

    public boolean isFormatedFields() {
        return jrbFieldsFormatted.isSelected();
    }

    public Character getDelimiter() {
        if (jrbTube.isSelected()) {
            return '|';
        }
        if (jrbTab.isSelected()) {
            return '\t';
        }
        if (jrbComma.isSelected()) {
            return ',';
        }
        if (jrbOther.isSelected()) {
            return jtfOther.getText().charAt(0);
        }
        return null;
    }

    public boolean isPrintFileLine() {
        return jcbPrintFileLine.isSelected();
    }

    public boolean isAllFields() {
        return jcbPrintFileLine.isSelected();
    }

    public boolean isHeaderOnTop() {
        return jrbHeaderOnTop.isSelected();
    }

    public boolean shouldAccessFiles() {
        return jcbAccessFiles.isSelected();
    }

    public boolean shouldPrintRecordType() {
        return jcbPrintRecordType.isSelected();
    }

    public boolean isLimitQueryResults() {
        return jcbLimitQueryResults.isSelected();
    }

    public int getMaxQueryLines() {
        return (Integer) jsMaxQueryLines.getValue();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgOutputFormat = new javax.swing.ButtonGroup();
        btgAllFields = new javax.swing.ButtonGroup();
        btgFieldDelimiter = new javax.swing.ButtonGroup();
        btgHeaders = new javax.swing.ButtonGroup();
        jpQuerySettings = new javax.swing.JPanel();
        jsMaxQueryLines = new javax.swing.JSpinner();
        jcbSort = new javax.swing.JCheckBox();
        jcbLimitQueryResults = new javax.swing.JCheckBox();
        jpOutputFormat = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jrbExcel = new javax.swing.JRadioButton();
        jrbSimple = new javax.swing.JRadioButton();
        jrbFull = new javax.swing.JRadioButton();
        jPanel10 = new javax.swing.JPanel();
        jpDelimiter = new javax.swing.JPanel();
        jrbComma = new javax.swing.JRadioButton();
        jrbTab = new javax.swing.JRadioButton();
        jrbTube = new javax.swing.JRadioButton();
        jPanel9 = new javax.swing.JPanel();
        jrbOther = new javax.swing.JRadioButton();
        jtfOther = new javax.swing.JTextField();
        jpReportContent = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jcbPrintFileLine = new javax.swing.JCheckBox();
        jcbPrintRecordType = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jcbAccessFiles = new javax.swing.JCheckBox();
        jPanel7 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jrbHeaderOnTop = new javax.swing.JRadioButton();
        jrbPrependHeader = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        jrbAllFields = new javax.swing.JRadioButton();
        jrbFieldsFormatted = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jtfOutFile = new javax.swing.JTextField();
        jbChooseFile = new javax.swing.JButton();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        jpQuerySettings.setBorder(javax.swing.BorderFactory.createTitledBorder("Query settings"));

        jsMaxQueryLines.setModel(new javax.swing.SpinnerNumberModel(2000, 0, null, 1));

        jcbSort.setSelected(true);
        jcbSort.setText("sort results (uncheck for huge amount of data)");

        jcbLimitQueryResults.setSelected(true);
        jcbLimitQueryResults.setText("Limit results in a query - max:");
        jcbLimitQueryResults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbLimitQueryResultsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpQuerySettingsLayout = new javax.swing.GroupLayout(jpQuerySettings);
        jpQuerySettings.setLayout(jpQuerySettingsLayout);
        jpQuerySettingsLayout.setHorizontalGroup(
                jpQuerySettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jpQuerySettingsLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jpQuerySettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jpQuerySettingsLayout.createSequentialGroup()
                                                .addComponent(jcbLimitQueryResults)
                                                .addGap(18, 18, 18)
                                                .addComponent(jsMaxQueryLines, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jcbSort))
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        jpQuerySettingsLayout.setVerticalGroup(
                jpQuerySettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jpQuerySettingsLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jpQuerySettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jcbLimitQueryResults)
                                        .addComponent(jsMaxQueryLines, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcbSort)
                                .addContainerGap())
        );

        add(jpQuerySettings);

        jpOutputFormat.setBorder(javax.swing.BorderFactory.createTitledBorder("Output format"));

        btgOutputFormat.add(jrbExcel);
        jrbExcel.setText("Excel");
        jrbExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbExcelActionPerformed(evt);
            }
        });

        btgOutputFormat.add(jrbSimple);
        jrbSimple.setSelected(true);
        jrbSimple.setText("simple");
        jrbSimple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbSimpleActionPerformed(evt);
            }
        });

        btgOutputFormat.add(jrbFull);
        jrbFull.setText("Full");
        jrbFull.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbFullActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
                jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jrbSimple)
                                        .addComponent(jrbExcel)
                                        .addComponent(jrbFull))
                                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
                jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jrbSimple)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jrbExcel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jrbFull)
                                .addContainerGap())
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jpDelimiter.setBorder(javax.swing.BorderFactory.createTitledBorder("field delimiter"));

        btgFieldDelimiter.add(jrbComma);
        jrbComma.setText("Comma");
        jrbComma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbCommaActionPerformed(evt);
            }
        });

        btgFieldDelimiter.add(jrbTab);
        jrbTab.setText("Tab");
        jrbTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbTabActionPerformed(evt);
            }
        });

        btgFieldDelimiter.add(jrbTube);
        jrbTube.setSelected(true);
        jrbTube.setText("|");
        jrbTube.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbTubeActionPerformed(evt);
            }
        });

        jPanel9.setLayout(new javax.swing.BoxLayout(jPanel9, javax.swing.BoxLayout.LINE_AXIS));

        btgFieldDelimiter.add(jrbOther);
        jrbOther.setText("Other");
        jrbOther.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbOtherActionPerformed(evt);
            }
        });
        jPanel9.add(jrbOther);

        jtfOther.setColumns(1);
        jPanel9.add(jtfOther);

        javax.swing.GroupLayout jpDelimiterLayout = new javax.swing.GroupLayout(jpDelimiter);
        jpDelimiter.setLayout(jpDelimiterLayout);
        jpDelimiterLayout.setHorizontalGroup(
                jpDelimiterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jpDelimiterLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jpDelimiterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jrbComma)
                                        .addComponent(jrbTab)
                                        .addComponent(jrbTube))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpDelimiterLayout.setVerticalGroup(
                jpDelimiterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jpDelimiterLayout.createSequentialGroup()
                                .addComponent(jrbTube)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jrbComma)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jrbTab)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16))
        );

        jpReportContent.setBorder(javax.swing.BorderFactory.createTitledBorder("Report content"));

        jcbPrintFileLine.setText("Print file:line");

        jcbPrintRecordType.setSelected(true);
        jcbPrintRecordType.setText("print record type");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jcbPrintRecordType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jcbPrintFileLine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jcbPrintFileLine)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcbPrintRecordType)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jcbAccessFiles.setSelected(true);
        jcbAccessFiles.setText("access log files while printing (uncheck for huge amount of data)");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 345, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jcbAccessFiles)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 52, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(jcbAccessFiles)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btgHeaders.add(jrbHeaderOnTop);
        jrbHeaderOnTop.setText("field headers on top");

        btgHeaders.add(jrbPrependHeader);
        jrbPrependHeader.setSelected(true);
        jrbPrependHeader.setText("print at header:field");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jrbHeaderOnTop)
                                        .addComponent(jrbPrependHeader))
                                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jrbHeaderOnTop)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jrbPrependHeader)
                                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btgAllFields.add(jrbAllFields);
        jrbAllFields.setText("all fields from request");
        jrbAllFields.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbAllFieldsActionPerformed(evt);
            }
        });

        btgAllFields.add(jrbFieldsFormatted);
        jrbFieldsFormatted.setSelected(true);
        jrbFieldsFormatted.setText("fields from format");
        jrbFieldsFormatted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbFieldsFormattedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jrbAllFields)
                                        .addComponent(jrbFieldsFormatted))
                                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jrbAllFields)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jrbFieldsFormatted)
                                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
        );

        javax.swing.GroupLayout jpReportContentLayout = new javax.swing.GroupLayout(jpReportContent);
        jpReportContent.setLayout(jpReportContentLayout);
        jpReportContentLayout.setHorizontalGroup(
                jpReportContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jpReportContentLayout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jpReportContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpReportContentLayout.setVerticalGroup(
                jpReportContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jpReportContentLayout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(jpReportContentLayout.createSequentialGroup()
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
                jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel10Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jpDelimiter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(jpReportContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
                jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel10Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jpDelimiter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jpReportContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
        );

        javax.swing.GroupLayout jpOutputFormatLayout = new javax.swing.GroupLayout(jpOutputFormat);
        jpOutputFormat.setLayout(jpOutputFormatLayout);
        jpOutputFormatLayout.setHorizontalGroup(
                jpOutputFormatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jpOutputFormatLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        jpOutputFormatLayout.setVerticalGroup(
                jpOutputFormatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jpOutputFormatLayout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34))
                        .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        add(jpOutputFormat);

        jLabel1.setText("Output file");

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));
        jPanel4.add(jtfOutFile);

        jbChooseFile.setText("...");
        jbChooseFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbChooseFileActionPerformed(evt);
            }
        });
        jPanel4.add(jbChooseFile);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel3);
    }// </editor-fold>//GEN-END:initComponents

    private void jbChooseFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbChooseFileActionPerformed
        if (chooser == null) {
            chooser = new JFileChooser();
            FileNameExtensionFilter filter = new FileNameExtensionFilter(
                    "TXT & SCV Files", "txt", "csv");
            chooser.setFileFilter(filter);

        }
        chooser.setCurrentDirectory(new File(jtfOutFile.getText()).getAbsoluteFile().getParentFile());
        int returnVal = chooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            jtfOutFile.setText(chooser.getSelectedFile().getAbsoluteFile().getAbsolutePath());
//            System.out.println("You chose to open this file: "
//                    + chooser.getSelectedFile().getName());
        }

    }//GEN-LAST:event_jbChooseFileActionPerformed

    private void setHeadersEnable() {
        boolean isEnabled = jrbAllFields.isSelected();
        jrbHeaderOnTop.setEnabled(isEnabled);
        jrbPrependHeader.setEnabled(isEnabled);
    }

    private void jrbAllFieldsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbAllFieldsActionPerformed
        setHeadersEnable();

    }//GEN-LAST:event_jrbAllFieldsActionPerformed

    private void jrbFieldsFormattedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbFieldsFormattedActionPerformed
        setHeadersEnable();
    }//GEN-LAST:event_jrbFieldsFormattedActionPerformed

    private void setSeparatorEnabled() {
        boolean isEnabled = !jrbFull.isSelected();
        jrbTube.setEnabled(isEnabled);
        jrbComma.setEnabled(isEnabled);
        jrbOther.setEnabled(isEnabled);
        jrbTab.setEnabled(isEnabled);
        jtfOther.setEnabled(isEnabled);
        jpDelimiter.setEnabled(isEnabled);
        jpReportContent.setEnabled(isEnabled);
        jcbPrintFileLine.setEnabled(isEnabled);
        jcbPrintRecordType.setEnabled(isEnabled);
        jrbAllFields.setEnabled(isEnabled);
        jrbFieldsFormatted.setEnabled(isEnabled);
        jrbHeaderOnTop.setEnabled(isEnabled);
        jrbHeaderOnTop.setEnabled(isEnabled);
        jrbPrependHeader.setEnabled(isEnabled);
        jcbAccessFiles.setEnabled(isEnabled);
        setHeadersEnable();

    }

    private void jrbSimpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbSimpleActionPerformed
        setSeparatorEnabled();
    }//GEN-LAST:event_jrbSimpleActionPerformed

    private void jrbExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbExcelActionPerformed
        setSeparatorEnabled();
    }//GEN-LAST:event_jrbExcelActionPerformed

    private void jrbFullActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbFullActionPerformed
        setSeparatorEnabled();
    }//GEN-LAST:event_jrbFullActionPerformed

    private void jcbLimitQueryResultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbLimitQueryResultsActionPerformed
        jsMaxQueryLines.setEnabled(jcbLimitQueryResults.isSelected());
    }//GEN-LAST:event_jcbLimitQueryResultsActionPerformed

    private void jrbTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbTabActionPerformed
        enableJtfOther();
    }//GEN-LAST:event_jrbTabActionPerformed

    private void jrbOtherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbOtherActionPerformed
        enableJtfOther();
    }//GEN-LAST:event_jrbOtherActionPerformed

    private void jrbTubeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbTubeActionPerformed
        enableJtfOther();
    }//GEN-LAST:event_jrbTubeActionPerformed

    private void jrbCommaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbCommaActionPerformed
        enableJtfOther();
    }//GEN-LAST:event_jrbCommaActionPerformed
    // End of variables declaration//GEN-END:variables

    private void enableJtfOther() {
        boolean isEnabled = jrbOther.isSelected();
        jtfOther.setEnabled(isEnabled);
        if (isEnabled) {
            jtfOther.requestFocus();
        }
    }

    void setOutDir(String logbrDir) {
        jtfOutFile.setText(logbrDir);
    }

    int getRecordsLimit() {
        if (jcbLimitQueryResults.isSelected()) {
            return getMaxQueryLines();
        } else {
            return -1;
        }
    }
}
