package com.myutils.logbrowser.inquirer;

public enum IDType {
    UNKNOWN,
    UUID,
    ConnID,
    OCSSID,
    OCSRecordHandle,
    ORSSID,
    IxnID,
    ReferenceID,
    OCSChainID,
    CG,
    DN,
    AGENT,
    CGDBID,
    PLACE,
    IxnQueue,
    OCSCampaign,
    OCSCampaignDBID,
    GMSSESSION,
    SIPCallID,
    TLibRefID,
    JSONID,
    SIPHandlerID,
    SIPTriggerID,
    TLIBID,
    SIPID,
    PEERIP,
    ORSCallID,
    MCPCallID,
    JSessionID,
    GWS_DeviceID,
    BrowserClientID,
    WWEUserID,
    ANYPARAM,
}
