/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.myutils.logbrowser.inquirer;

import com.myutils.logbrowser.indexer.FileInfoType;
import com.myutils.logbrowser.inquirer.gui.JPSecSelect;
import javax.swing.ButtonGroup;

/**
 *
 * @author ssydoruk
 */
public class TLibDelaysConfig extends javax.swing.JPanel {

    private final JPSecSelect jpTimeDiff;

    /**
     * Creates new form TLibDelaysConfig
     */
    public TLibDelaysConfig() {
        initComponents();
//        jpAppSelect.setBorder(new BevelBorder(BevelBorder.RAISED));

        jpTimeDiff = new JPSecSelect(0, 500);
        jpTimeDiff.setTextStart("Show if difference is more than");
        jpTimeDiff.setTextEnd("ms");
        jpAppSettings.add(jpTimeDiff);

    }

    public int getSeconds() {
        return jpTimeDiff.getSeconds();
    }

    private final ButtonGroup group = new ButtonGroup();
    private final FileInfoType ft = FileInfoType.type_Unknown;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpAppSettings = new javax.swing.JPanel();
        jpTimeSettings = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));
        add(jpAppSettings);
        add(jpTimeSettings);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jpAppSettings;
    private javax.swing.JPanel jpTimeSettings;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the ft
     */
    public FileInfoType getFt() {
        return ft;
    }

}
